theme: minima
title: Keeping Record
author: Kevin L. Eldridge
email: kevineldridge93@gmail.com
description: > i am keeping record of the thing I do during the day and thought 
i might have my feeling How many time the bossman cusses at me and if it 
fucking pisses me off are not so instead of keeping up with Kardashians keep up with my Fat ass....

# social links
twitter_username: Kev64321334
github_username:  connect17

show_excerpts: true # set to false to remove excerpts on the homepage
